name: simple workflow

on:
    push:
        branches:
          - main

jobs:
    build:
      runs-on: ubuntu-latest

      steps: 
        - uses: actions/checkout@v4
        - name: run a oneline script 
          run: echo "Hello world"
        