# jobs in github actions

name: Demo Workflows

on:
    push:
        branches:
          - master

jobs:
    build:
        name: build
        needs: [Development]
        steps:
          - name: Build and eploy on cloud

    dev:
        name: Development
        steps:
          - name: Run the Development

    test:
        name: testing
        steps:
          - name: testing the application